version: 2.1

jobs:
  detect-languages:
    docker:
    - image: circleci/node:latest # Use a Node.js image (can be changed)
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          sudo apt update
          sudo apt install -y findutils grep
    - run:
        name: Detect Programming Languages
        command: |
          chmod +x detect_languages.sh
          .circleci/detect_languages.sh

workflows:
  version: 2
  detect_languages:
    jobs:
    - detect-languages
